[package]
name = "cgltf-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.69.2"
cc = "1.0.83"

[dependencies]
byte-strings = "0.3.1"
